spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://localhost:3306/itimersalesforce
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
server:
    port: 9000